name: Bug Report
description: Report a bug or issue with Spell History
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Addon Version
      description: What version of Spell History are you using?
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: input
    id: wow-version
    attributes:
      label: WoW Version
      description: What version of World of Warcraft are you using?
      placeholder: e.g., 12.0.0
    validations:
      required: true

  - type: dropdown
    id: game-type
    attributes:
      label: Game Type
      description: Which version of WoW are you playing?
      options:
        - Retail (Midnight)
        - Classic Era
        - Cataclysm Classic
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Messages
      description: If you received any error messages, paste them here
      placeholder: Paste any Lua errors from BugSack or similar addons...
      render: lua

  - type: textarea
    id: other-addons
    attributes:
      label: Other Addons
      description: List any other addons you have installed that might be related
      placeholder: List other addons...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem
      placeholder: Add screenshots or additional information...
